language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
before_install:
  - pip install -U pip setuptools virtualenvwrapper
  - source $(which virtualenvwrapper.sh)
  - wipeenv
install:
  - pip install .
script: python setup.py test
